data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: hubertsoft
  encoder_ckpt: pretrain/hubert/hubert-soft-0d54a1f4.pt
  encoder_hop_size: 320
  encoder_out_channels: 256
  encoder_sample_rate: 16000
  f0_extractor: parselmouth
  f0_max: 800
  f0_min: 65
  sampling_rate: 44100
  train_path: data/train
  valid_path: data/val
device: cuda
enhancer:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
env:
  expdir: exp/combsub-test
  gpu_id: 0
loss:
  fft_max: 2048
  fft_min: 256
  n_scale: 4
model:
  n_spk: 1
  type: CombSubFast
train:
  batch_size: 24
  cache_all_data: true
  cache_device: cuda
  cache_fp16: true
  epochs: 100000
  interval_log: 10
  interval_val: 2000
  lr: 0.0005
  num_workers: 2
  save_opt: false
  weight_decay: 0
